config/routes.rb
Rails.application.routes.draw do
  # 会員側ユーザ機能
  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
  }

  # 管理者側ユーザ機能
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
  }

  devise_for :users

  # 管理者側ルーティング設定
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    get '/' => 'homes#top', as: 'top'
  end

  # 会員側ルーティング設定
  scope module: :public do
    # homesコントローラのルーティング
    root to: 'homes#top'
    get '/top' => 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    # itemsコントローラのルーティング
    resources :items, only: [:index, :show]
    # customersコントローラのルーティング
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    # cart_itemsコントローラのルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    # ordersコントローラのルーティング
    resources :orders, only: [:new, :index, :show] do
      collection do
        post 'confirm'
        get 'thanks'
        post 'definition'
      end
    end
    # addressesコントローラのルーティング
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def active_for_authentication?
    super && (self.is_active == false)
  end
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  # layout 'top'
  
  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_active)
  end
    
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  protect_from_forgery
  
  def after_sign_up_path_for(resource)
    customer_path(current_customer)
  end
  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
<div class="container my-5">
  <div class="row">
    <div class="offset-md-1 col-md-10 my-3">
      <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
    </div>
  </div>
  
  
  <div class="offset-md-1 col-md-10">
    <div class="mx-auto">
      
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3">
          <p>会員ID</p>
        </div>
        <div class="col-md-1">
          <%= @customer.id %>
        </div>
      </div>
      
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3">
          <p>氏名</p>
        </div>
        <div class="col-md-3">
          <%= f.text_field :last_name, size: 30 %>
        </div>
        <div class="col-md-1">
          <%= f.text_field :first_name, size: 30 %>
        </div>
      </div>
      
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3">
          <p>フリガナ</p>
        </div>
        <div class="col-md-3">
          <%= f.text_field :last_name_kana, size: 30 %>
        </div>
        <div class="col-md-1">
          <%= f.text_field :first_name_kana, size: 30 %>
        </div>
      </div>
      
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3">
          <p>郵便番号</p>
        </div>
        <div class="col-md-1">
          <%= f.text_field :postal_code, size: 30 %>
        </div>
      </div>
      
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3">
          <p>住所</p>
        </div>
        <div class="col-md-1">
          <%= f.text_field :address, size: 100 %>
        </div>
      </div>
      
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3">
          <p>電話番号</p>
        </div>
        <div class="col-md-1">
          <%= f.text_field :telephone_number, size: 30 %>
        </div>
      </div>
      
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3">
          <p>メールアドレス</p>
        </div>
        <div class="col-md-1">
          <%= f.text_field :email, size: 30 %>
        </div>
      </div>
      
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3">
          <p>会員ステータス</p>
        </div>
        <div class="done col-md-3">
          <div class="row">
            <div>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, '退会', value: true %>
            </div>
            <div class="col-md-1"></div>
            <div>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, '有効', value: false %>
            </div>
          </div>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-left">
        </div>
        <div class="col-md-2 text-right">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>

</div>
<% end %>

app/views/admin/customers/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-sm-1 col-sm-10 my-3">
      <h4>会員一覧</h4>
    </div>
  </div>

  <div class="row mt-3">
    <div class="offset-sm-2 col-sm-8 my-3">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customers| %>
          <tr>
            <td>
              <%= customers.id %>
            </td>
            <td>
              <%= link_to customers.last_name, admin_customer_path(customers.id) %>
            </td>
            <td>
              <%= customers.email %>
            </td>
            <td>
              <%= customers.is_active?? '退会済み': '有効' %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col float-center">
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#">Next</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#" tabindex="-1">Last</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>

</div>

app/views/admin/customers/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-md-1 col-md-10 my-3">
      <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
    </div>
  </div>
  
  <div class="row">
    <div class="offset-md-1 col-md-10">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %> <%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><%= @customer.is_active %></td>
          </tr>
        </tbody>
      </table>
      <div class="offset-md-2">
        <%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-success mx-5" %>
        <%= link_to '注文履歴一覧を見る', admin_orders_path, class: "btn btn-primary mx-5" %>
      </div>
    </div>
  </div>

</div>