config/routes.rb
Rails.application.routes.draw do
  # 会員側ユーザ機能
  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
  }

  # 管理者側ユーザ機能
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
  }

  devise_for :users

  # 管理者側ルーティング設定
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    get '/' => 'homes#top', as: 'top'
  end

  # 会員側ルーティング設定
  scope module: :public do
    # homesコントローラのルーティング
    root to: 'homes#top'
    get '/top' => 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    # itemsコントローラのルーティング
    resources :items, only: [:index, :show]
    # customersコントローラのルーティング
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    # cart_itemsコントローラのルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    # ordersコントローラのルーティング
    resources :orders, only: [:new, :index, :show] do
      collection do
        post 'confirm'
        get 'thanks'
        post 'definition'
      end
    end
    # addressesコントローラのルーティング
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  def order_address
	  self.postal_code + self.address + self.name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def active_for_authentication?
    super && (self.is_active == false)
  end
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  belongs_to :genres, class_name: 'Message', foreign_key: 'genre_id', optional: true
  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  
  #注文の全ての数量合計
  def sum_order_items
    self.order_items.all.sum(:amount)
  end

  #注文の合計金額
  def total_payment
    array = []
    self.order_items.each do |order_item|
       array << order_item.price * order_item.amount
   end
    array.sum
  end
  
  enum payment_method: { クレジットカード: 0, 銀行振込: 1}
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
  
  enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 3, 製作完了: 4 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genrenew = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.all
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
    # if @item.save
    #   flash[:notice] = "You have created item successfully"
    #   redirect_to admin_item_path(@item)
    # else
    #   render 'new'
    # end
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "You have updated item successfully"
      redirect_to admin_item_path(@item)
    else
      render 'edit'
    end
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.all
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_orders_path(@order)
  end
  
  private
  def order_params
    params.require(:order).permit(:status)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end
  
  # def after_sign_up_path_for(resource)
  #   case resource
  #   when Customer
  #     customer_path(current_customer)
  #   when Admin
  #     admin_orders_path
  #   end
  # end

  # def after_sign_in_path_for(resource)
  #   case resource
  #   when Customer
  #     customer_path(current_customer)
  #   when Admin
  #     admin_orders_path
  #   end
  # end

  def after_sign_out_path_for(resource)
    if Customer
      top_path
    else
      new_admin_session_path
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="offset-sm-1 col-sm-10 my-3">
      <h4>ジャンル編集</h4>
    </div>
  </div>
  
  <%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
  <div class="row my-5">
    <div class="col-md-2 text-center">
      <p>ジャンル名</p>
    </div>
    <div class="col-md-3 text-center">
      <%= f.text_field :name, size: 20 %>
    </div>
    <div class="col-md-1 text-center">
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-sm-1 col-sm-10 my-3">
      <h4>ジャンル一覧・追加</h4>
    </div>
  </div>

  <%= form_with model: @genrenew, url: admin_genres_path, local: true do |f| %>
  <div class="row my-5">
    <div class="col-md-2 text-center">
      <p>ジャンル名</p>
    </div>
    <div class="col-md-3 text-center">
      <%= f.text_field :name, placeholder: "ジャンル名", size: 20 %>
    </div>
    <div class="col-md-1 text-center">
      <%= f.submit "新規登録", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
  
  <div class="row my-5">
    <div class="col-md-6">
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="text-center">ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |g| %>
          <tr>
            <td><%= g.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(g), class: "btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
</div>

app/views/admin/items/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-sm-2 col-sm-8 my-3">
      <h4>商品新規登録</h4>
    </div>
  </div>
  
  <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
  <div class="offset-md-2 col-md-8">
    <div class="mx-auto">
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>商品画像</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.attachment_field :image, aurofocus: true, placeholder: "ファイルを選択" %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>商品名</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.text_field :name, placeholder: "商品名", size: 30 %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>商品説明</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.text_area :introduction, placeholder: "ここに説明を記述します", size: "30x6" %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>ジャンル</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--", size: "30", class: "form-control" %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>税抜価格</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.text_field :price, placeholder: "1000", size: 30 %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>販売ステータス</p>
        </div>
        <div class="done col-md-3">
          <div class="row">
            <div>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, '販売中', value: true %>
            </div>
            <div class="col-md-1"></div>
            <div>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, '販売停止中', value: false %>
            </div>
          </div>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-left">
        </div>
        <div class="col-md-2 text-right">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/admin/items/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12">
      <h2 class="float-left">商品一覧</h2>
      <%= link_to " + ", new_admin_item_path, class:"btn btn-outline-dark float-right" %>
    </div>
  </div>

  <div class="row mt-5">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |items| %>
          <tr>
            <td>
              <%= items.id %>
            </td>
            <td>
              <%= link_to items.name, admin_item_path(items.id) %>
            </td>
            <td>
              <%= items.price %>
            </td>
            <td>
              
            </td>
            <td>
              <%= items.is_active?? '販売中': '販売停止中' %>
            </td>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>
  <div class="row mt-5">
    <div class="col float-center">
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#">Next</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#" tabindex="-1">Last</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
 </div>

app/views/admin/items/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-sm-2 col-sm-8 my-3">
      <h4>商品新規登録</h4>
    </div>
  </div>
  
  <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
  <div class="offset-md-2 col-md-8">
    <div class="mx-auto">
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>商品画像</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.attachment_field :image, aurofocus: true, placeholder: "ファイルを選択" %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>商品名</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.text_field :name, placeholder: "商品名", size: 30 %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>商品説明</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.text_area :introduction, placeholder: "ここに説明を記述します", size: "30x6" %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>ジャンル</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--", size: "30", class: "form-control" %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>税抜価格</p>
        </div>
        <div class="col-md-1 text-center">
          <%= f.text_field :price, placeholder: "1000", size: 30 %>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-center">
          <p>販売ステータス</p>
        </div>
        <div class="done col-md-3">
          <div class="row">
            <div>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, '販売中', value: true %>
            </div>
            <div class="col-md-1"></div>
            <div>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, '販売停止中', value: false %>
            </div>
          </div>
        </div>
      </div>
      <div class="row" style="font-size: 13px; margin-top: 10px;">
        <div class="col-md-3 text-left">
        </div>
        <div class="col-md-2 text-right">
          <%= f.submit "新規登録", class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/admin/items/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-sm-2 col-sm-8 my-3">
      <h4>商品詳細</h4>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-3">
      <%= attachment_image_tag @item, :image, format: 'jpeg', fallback: "no_image.jpeg", size:"300x300" %>
    </div>
    <div class="col-md-8 offset-md-1">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td></td>
          </tr>
          <tr>
            <td>税込価格<br>(税抜価格)</td>
            <td><%= @item.price %> 円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td><%= @item.is_active?? '販売中': '販売停止中' %></td>
          </tr>
        </tbody>
      </table>
      <div>
        <%= link_to '編集する', edit_admin_item_path(@item.id), class: "btn btn-success" %>
      </div>
    </div>
  </div>

</div>

app/views/admin/orders/index.html.erb
<div class="container my-5">
  <div class="row">
    <h4>注文履歴一覧</h4>
  </div>

  <div class="row mt-5">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |orders| %>
          <tr>
            <td>
              <%= link_to orders.created_at, admin_order_path(orders.id) %>
            </td>
            <td>
              <%= orders.customer.last_name %><%= orders.customer.first_name %>
            </td>
            <td>
              <%= orders.order_items.sum(:amount) %>
            </td>
            <td>
              <%= orders.status %>
            </td>
          </tr>
        <% end %>
      </tbody>
      
    </table>
  </div>
 </div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="admin-order-show pt-5">
    <h4 class="pb-3">注文履歴詳細</h4>
    <table class="w-100 admin-order-details admin-customer-show">
      <tr class="row pb-2">
        <th class="col-md-2">購入者</th>
        <td class="col-md-10">
          <%= link_to @order.customer.last_name, admin_customer_path(@order.customer), class: "text-dark" %>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">注文日</th>
        <td class="col-md-10">
          <%= @order.created_at %>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">配送先</th>
        <td class="col-md-10">
          <div class="admin-order-post mb-2">
            <span>
              〒<%= @order.postal_code.to_s.insert(3, "-") %>
            </span>
            <span>
              <%= @order.address %>
            </span>
          </div>
          <div class="admin-order-post">
            <%= @order.name %>
          </div>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">支払方法</th>
        <td class="col-md-10">
          <%= @order.payment_method %>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">注文ステータス</th>
        <td class="col-md-10">
          <%= form_with model: @order, url: admin_order_path(@order), local: true do |f| %>
            <%= f.select :status, options_for_select(Order.statuses, selected: Order.statuses[@order.status]) %>
            <%= f.submit "更新", class: "btn btn-success ml-4"%>
          <% end %>
        </td>
      </tr>
    </table>

    <div class="admin-order-bottom row mt-5 w-100">
      <table class="table admin-order-items col-md-8">
        <tr>
          <th class="table-active">商品名</th>
          <th class="table-active">単価（税込）</th>
          <th class="text-center table-active">数量</th>
          <th class="text-center table-active">小計</th>
          <th class="table-active">製作ステータス</th>
        </tr>
        <% @order.order_items.each do |order_item| %>
          <tr>
            <td><%= order_item.item.name %></td>
            <td><%= order_item.price.to_s(:delimited) %></td>
            <td class="text-center"><%= order_item.amount.to_s(:delimited) %></td>
            <td class="text-center"><%= (order_item.price.to_i * order_item.amount.to_i).to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_item, url: admin_order_item_path(order_item), local: true do |f| %>
                <%= f.select :making_status, options_for_select(OrderItem.making_statuses, selected: OrderItem.making_statuses[order_item.making_status]) %>
                <%= f.submit "更新", class: "btn btn-success ml-3" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <table class="admin-order-details col-md-3 ml-auto mt-auto admin-customer-show">
        <tr>
          <th>商品合計</th>
          <td class="text-right"><%= @order.total_payment.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <% @order.shipping_cost = '700' %>
          <td class="text-right"><%= @order.shipping_cost.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td class="text-right"><%= (@order.total_payment.to_i + @order.shipping_cost.to_i).to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>