config/routes.rb
Rails.application.routes.draw do
  # 会員側ユーザ機能
  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
  }

  # 管理者側ユーザ機能
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
  }

  devise_for :users

  # 管理者側ルーティング設定
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    get '/' => 'homes#top', as: 'top'
  end

  # 会員側ルーティング設定
  scope module: :public do
    # homesコントローラのルーティング
    root to: 'homes#top'
    get '/top' => 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    # itemsコントローラのルーティング
    resources :items, only: [:index, :show]
    # customersコントローラのルーティング
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    # cart_itemsコントローラのルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    # ordersコントローラのルーティング
    resources :orders, only: [:new, :index, :show] do
      collection do
        post 'confirm'
        get 'thanks'
        post 'definition'
      end
    end
    # addressesコントローラのルーティング
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  def order_address
	  self.postal_code + self.address + self.name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def active_for_authentication?
    super && (self.is_active == false)
  end
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  belongs_to :genres, class_name: 'Message', foreign_key: 'genre_id', optional: true
  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  
  #注文の全ての数量合計
  def sum_order_items
    self.order_items.all.sum(:amount)
  end

  #注文の合計金額
  def total_payment
    array = []
    self.order_items.each do |order_item|
       array << order_item.price * order_item.amount
   end
    array.sum
  end
  
  enum payment_method: { クレジットカード: 0, 銀行振込: 1}
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
  
  enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 3, 製作完了: 4 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end
  
  # def after_sign_up_path_for(resource)
  #   case resource
  #   when Customer
  #     customer_path(current_customer)
  #   when Admin
  #     admin_orders_path
  #   end
  # end

  # def after_sign_in_path_for(resource)
  #   case resource
  #   when Customer
  #     customer_path(current_customer)
  #   when Admin
  #     admin_orders_path
  #   end
  # end

  def after_sign_out_path_for(resource)
    if Customer
      top_path
    else
      new_admin_session_path
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <span>Nagano Cake</span>
          </a>
          
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li class="customer-name text-center mx-5 my-1">
                  ようこそ、<%= current_customer.last_name %> さん
                </li>
                <li class="nav-item">
                  <%= link_to " マイページ", customer_path(current_customer), class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " 商品一覧", items_path, class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " カート", cart_items_path, class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " ログアウト", destroy_customer_session_path, method: :delete, class:"nav-link text-dark" %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to " 商品一覧", admin_items_path, class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " 会員一覧", admin_customers_path, class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " 注文履歴一覧", admin_orders_path, class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " ジャンル一覧", admin_genres_path, class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link text-dark" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to " About", about_path, class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " 商品一覧", items_path, class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " 新規登録", new_customer_registration_path, class:"nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to " ログイン", new_customer_session_path, class:"nav-link text-dark" %>
                </li>
              <% end %>
            </ul>
          </div>
          
        </div>
      </nav>
    </header>
    
    <main>
      <% if flash[:notice] %>
        <p id ="notice">
          <%= flash[:notice] %>
        </p>
      <% else %>
      <% end %>
      <%= yield %>
    </main>
    
    <footer></footer>
  </body>
</html>